development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:8590c3d128bd2894f7398242a227369e@greeneye.redistogo.com:11357/
  channel_prefix: ot-example_production
